In [14]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [15]:
x1=np.random.randint(1,10, size=7)

In [16]:
x2=np.random.randint(1,10, size=(3,7))

In [17]:
x3=np.random.randint(1,10, size=(2,3,7))

In [18]:
x4=np.random.randint(1,10, size=(4,2,3,7))

In [22]:
x1

array([1, 7, 3, 4, 7, 3, 6])

In [24]:
x1[2]

3

In [25]:
x1[2:5]

array([3, 4, 7])

In [27]:
x2[0:2]

array([[5, 3, 4, 9, 9, 2, 8],
       [5, 5, 3, 9, 9, 1, 4]])

In [29]:
x2[0:2, 4:]

array([[9, 2, 8],
       [9, 1, 4]])

In [30]:
x3

array([[[8, 6, 1, 5, 6, 6, 4],
        [4, 1, 1, 5, 3, 5, 7],
        [5, 6, 6, 7, 4, 7, 3]],

       [[1, 5, 4, 1, 9, 3, 4],
        [5, 3, 1, 5, 7, 5, 5],
        [6, 2, 6, 1, 1, 8, 3]]])

In [31]:
x3[0:3]

array([[[8, 6, 1, 5, 6, 6, 4],
        [4, 1, 1, 5, 3, 5, 7],
        [5, 6, 6, 7, 4, 7, 3]],

       [[1, 5, 4, 1, 9, 3, 4],
        [5, 3, 1, 5, 7, 5, 5],
        [6, 2, 6, 1, 1, 8, 3]]])

In [32]:
x3[1:2]

array([[[1, 5, 4, 1, 9, 3, 4],
        [5, 3, 1, 5, 7, 5, 5],
        [6, 2, 6, 1, 1, 8, 3]]])

In [33]:
x3[0:2]

array([[[8, 6, 1, 5, 6, 6, 4],
        [4, 1, 1, 5, 3, 5, 7],
        [5, 6, 6, 7, 4, 7, 3]],

       [[1, 5, 4, 1, 9, 3, 4],
        [5, 3, 1, 5, 7, 5, 5],
        [6, 2, 6, 1, 1, 8, 3]]])

In [38]:
x3[0:2, 1]

array([[4, 1, 1, 5, 3, 5, 7],
       [5, 3, 1, 5, 7, 5, 5]])

In [42]:
x3[0:2, 1,3:5]

array([[5, 3],
       [5, 7]])

In [43]:
x4

array([[[[1, 1, 7, 3, 1, 1, 1],
         [8, 9, 2, 7, 7, 9, 8],
         [4, 1, 1, 9, 5, 3, 7]],

        [[9, 9, 1, 3, 2, 5, 7],
         [2, 8, 2, 4, 2, 8, 4],
         [5, 5, 3, 9, 2, 6, 4]]],


       [[[8, 2, 7, 7, 1, 9, 2],
         [9, 9, 4, 7, 9, 9, 3],
         [2, 5, 7, 1, 7, 7, 4]],

        [[8, 2, 5, 3, 8, 3, 7],
         [9, 9, 2, 2, 6, 2, 9],
         [4, 1, 8, 2, 1, 2, 7]]],


       [[[2, 9, 4, 4, 3, 4, 9],
         [2, 9, 4, 9, 2, 8, 3],
         [4, 6, 1, 6, 8, 6, 7]],

        [[1, 8, 5, 7, 2, 3, 3],
         [4, 2, 8, 3, 9, 2, 4],
         [9, 8, 7, 4, 6, 5, 9]]],


       [[[1, 2, 6, 4, 9, 5, 8],
         [7, 2, 8, 4, 8, 5, 7],
         [1, 8, 7, 5, 7, 6, 6]],

        [[7, 4, 8, 4, 2, 2, 3],
         [2, 1, 7, 9, 4, 5, 2],
         [3, 5, 4, 1, 1, 9, 3]]]])

In [45]:
x4[0:4]

array([[[[1, 1, 7, 3, 1, 1, 1],
         [8, 9, 2, 7, 7, 9, 8],
         [4, 1, 1, 9, 5, 3, 7]],

        [[9, 9, 1, 3, 2, 5, 7],
         [2, 8, 2, 4, 2, 8, 4],
         [5, 5, 3, 9, 2, 6, 4]]],


       [[[8, 2, 7, 7, 1, 9, 2],
         [9, 9, 4, 7, 9, 9, 3],
         [2, 5, 7, 1, 7, 7, 4]],

        [[8, 2, 5, 3, 8, 3, 7],
         [9, 9, 2, 2, 6, 2, 9],
         [4, 1, 8, 2, 1, 2, 7]]],


       [[[2, 9, 4, 4, 3, 4, 9],
         [2, 9, 4, 9, 2, 8, 3],
         [4, 6, 1, 6, 8, 6, 7]],

        [[1, 8, 5, 7, 2, 3, 3],
         [4, 2, 8, 3, 9, 2, 4],
         [9, 8, 7, 4, 6, 5, 9]]],


       [[[1, 2, 6, 4, 9, 5, 8],
         [7, 2, 8, 4, 8, 5, 7],
         [1, 8, 7, 5, 7, 6, 6]],

        [[7, 4, 8, 4, 2, 2, 3],
         [2, 1, 7, 9, 4, 5, 2],
         [3, 5, 4, 1, 1, 9, 3]]]])

In [46]:
x4[0:4, 0,2:3]

array([[[4, 1, 1, 9, 5, 3, 7]],

       [[2, 5, 7, 1, 7, 7, 4]],

       [[4, 6, 1, 6, 8, 6, 7]],

       [[1, 8, 7, 5, 7, 6, 6]]])

In [5]:
x3[0:4,0:3,0:2,2:4]

NameError: name 'x3' is not defined